### ISSUE TITLE
Iterator panics when any of the provided indices exceeds slice bound

### ISSUE THREAD

**Issue by darrenldl** [pdx-cs-rust/reorder#1]
In implementation of next function([line 69](https://github.com/pdx-cs-rust/reorder/blob/master/reorder.rs#L69))
```rust
impl<'a, T> Iterator for Reorder<'a, T> {
    type Item = &'a T;
    fn next(&mut self) -> Option<Self::Item> {
        if self.index >= self.posn.len() {
            return None;
        }
        let result = &self.slice[self.posn[self.index]];
        self.index += 1;
        Some(result)
    }
}
```
At line 75, the `&self.slice[self.posn[self.index]]` part will cause the program to panic if posn[x] exceeds length of slice for some x.

I am not sure if this is a deliberate design decision, but if it is, you should document this fairly explicitly.

Personally I'd prefer it to not panic and give back an error of some kind, my understanding is that the signature of `next` is fixed, but is it possible to make it so instead or using `type item = &'a T`, you have `type item = Result<&'a T>`? (I have never implemented an iterator, so I'm clueless and pardon for any errors).

**Comment by BartMassey** [comment]
It's a good point! Yes, it was a deliberate design decision, and you are quite right that it should be clearly documented. I don't think I want to complicate the iterator; offhand I can't think of any reason other than programmer error for an out-of-bounds index.

**Comment by BartMassey** [comment]
Upon review the documentation already stated that the iterator would panic if an index was out-of-bounds. I moved this sentence fragment to its own "Panics" section as is standard in Rust documentation. I also added a should-fail test of this behavior.

Thanks again for your comment!

**Comment by darrenldl** [comment]
Whoops, I didn't go through the documentation properly at all then, oh dear.

Moving into a separate panics section is still a good idea for people who miss text very often like me though, so that's good.

**Comment by BartMassey** [comment]
Agreed. Thanks again!
